name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t portfolio .

      - name: Save Docker image as tar
        run: |
          docker save -o portfolio.tar portfolio
          chmod +rwx portfolio.tar

      - name: Transfer Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: |
            ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: portfolio.tar
          target: /home/ubuntu/portfolio

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker load -i /home/ubuntu/portfolio/portfolio.tar
            docker compose -f portfolio/docker-compose.yml up -d
